import { StyleSheet, Text, View, TouchableOpacity, Platform } from "react-native";
import React, { useState } from "react";
import CustomText from "../../../../Components/CustomText";
import { colors } from "../../../../Utils/Colors";
import { verticalScale } from "react-native-size-matters";
import Octicons from 'react-native-vector-icons/Octicons'
import { moderateScale } from "react-native-size-matters";


const TermAndCondition = () => {
  const [check, setCheck] = useState(false)
  return (
    <View style={styles.mainContainer}>
      <TouchableOpacity
        activeOpacity={0.6}
        onPress={() => {
          setCheck(!check)

        }}
        style={styles.checkBox}>
        {
          check ? (
            <Octicons
              name="check"
              color={colors.gray}
              size={moderateScale(17)}
            // onPress={onPress}
            />

          ) : <></>

        }



      </TouchableOpacity>
      <View
        style={{
          marginHorizontal: 10,
          flexDirection: "row",
          width: "90%",
          alignItems: "center",
        }}
      >
        <CustomText
          label={
            "I agree this image was generated by me using AI and I am not uploading someone else’s work."
          }
          color={colors.pureBlack}
          // fontFamily={"inter"}
          //   textAlign={"center"}
          fontSize={10}
        ></CustomText>
        <View
          style={{
            marginTop: verticalScale(13),
            marginLeft: Platform.OS == "ios" ? verticalScale(-60) : verticalScale(-100)
          }}
        >
          <CustomText
            label={"Read More"}
            color={"#0C07FA"}
            // fontFamily={"inter"}
            textAlign={"center"}
            fontSize={10}
          />
        </View>
      </View>
    </View>
  );
};

export default TermAndCondition;

const styles = StyleSheet.create({
  mainContainer: {
    flexDirection: "row",
    alignItems: "center",
    // padding: 10,
    paddingHorizontal: 20
  },
  checkBox: {
    width: 22,
    height: 22,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 5,
    borderWidth: 1,
    borderColor: colors.gray,
  },
});
